{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.mysqlServiceName" . }}
  labels:
    app: {{ include "myapp.mysqlServiceName" . }}
spec:
  selector:
    app: {{ include "myapp.mysqlServiceName" . }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
  type: {{ .Values.mysql.service.type }}
{{- end }}
