{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.mysqlServiceName" . }}
  labels:
    app: {{ include "myapp.mysqlServiceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "myapp.mysqlServiceName" . }}
  template:
    metadata:
      labels:
        app: {{ include "myapp.mysqlServiceName" . }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: mysql-password
          ports:
            - containerPort: 3306
          resources:
{{ toYaml .Values.mysql.resources | indent 12 }}
          volumeMounts:
            {{- if .Values.mysql.persistence.enabled }}
            - name: mysql-data
              mountPath: /var/lib/mysql
            {{- end }}
      volumes:
        {{- if .Values.mysql.persistence.enabled }}
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "myapp.mysqlServiceName" . }}-pvc
        {{- end }}
{{- end }}
