apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName }}
  labels:
    app: {{ include "myapp.name" . }}
type: Opaque
data:
  mysql-root-password: {{ required "mysql.rootPassword is required" .Values.mysql.rootPassword | b64enc | quote }}
  mysql-password: {{ required "mysql.password is required" .Values.mysql.password | b64enc | quote }}
  mysql-user: {{ required "mysql.user is required" .Values.mysql.user | b64enc | quote }}
  mysql-database: {{ required "mysql.database is required" .Values.mysql.database | b64enc | quote }}
