name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (e.g. dev, prod)'
        required: true
        default: 'dev'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}
