name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (e.g. dev, prod)'
        required: true
        default: 'dev'  # Default to 'dev' if no input is provided

#  push:
#    branches:
#      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set up Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az --version

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
        id: setup-kubectl

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'
        id: setup-helm

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RG_NAME }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push WebApp Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app/src
          platforms: linux/amd64,linux/arm64  
          # file: ${{ env.WEBAPP_DOCKERFILE }}
          file: ./app/src/Dockerfile
          # tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.WEBAPP_IMAGE }}
          tags: ${{ secrets.DOCKER_USERNAME }}/webapp:1.0
          push: true
          
      - name: Build and Push MySQL Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app/src/services/db
          platforms: linux/amd64,linux/arm64
          # file: ${{ env.MYSQL_DOCKERFILE }}
          file: ./app/src/services/db/Dockerfile
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.MYSQL_IMAGE }}
          tags: ${{ secrets.DOCKER_USERNAME }}/mysql-custom:1.0
          push: true

      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/kubeconfig

      - name: Deploy with Helm
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig  # Set the kubeconfig environment variable
        run: |
          helm upgrade --install my-app ./helm --namespace default \
            --set name=foobar \
            -f ./helm/values.yaml \
            -f ./helm/values-secret.yaml

      # Step 9: Wait for 20 seconds to ensure deployment completes
      - name: Wait for 20 seconds
        run: |
          sleep 100

      # Step 10: Check the status of all resources in the AKS cluster
      - name: Check the status of all resources
        run: |
          kubectl get all --namespace default
