name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (e.g. dev, prod)'
        required: true
        default: 'dev'  # Default to 'dev' if no input is provided

#  push:
#    branches:
#      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az --version

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
        id: setup-kubectl

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'
        id: setup-helm

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RG_NAME }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push WebApp Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .  
          platforms: linux/amd64,linux/arm64  
          file: ${{ env.WEBAPP_DOCKERFILE }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.WEBAPP_IMAGE }}
          push: true
          
      - name: Build and Push MySQL Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ env.MYSQL_DOCKERFILE }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.MYSQL_IMAGE }}
          push: true

      - name: Deploy with Helm
        uses: deliverybot/helm@v1
        with:
          release: ${{ github.event.inputs.environment }}  
          namespace: 'default'   
          chart: './helm/'      
          # token: '${{ github.token }}'  
          values: |
            name: foobar   # Puedes poner tus valores específicos aquí
          value-files: >
            [
              "values.yaml", 
              "values-secret.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      # Step 9: Wait for 20 seconds to ensure deployment completes
      - name: Wait for 20 seconds
        run: |
          sleep 20

      # Step 10: Check the status of all resources in the AKS cluster
      - name: Check the status of all resources
        run: |
          kubectl get all --namespace default
