name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (e.g., dev, prod)'
        required: true
        default: 'dev'

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print environment
      run: echo "Deploying to the ${{ github.event.inputs.environment }} environment"
